# Copyright (c) 2026 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Flash Attention v4 unified public interface.

Exposes the framework-specific backend through a single stable import path:

    from flash_mask.interface import flash_attn_func, flash_attn_varlen_func

The backend is fixed at **install time** via the ``FLASH_ATTN_BACKEND``
environment variable passed to ``pip install`` / ``setup.py``:

    FLASH_ATTN_BACKEND=paddle pip install -e . --no-build-isolation   # default
    FLASH_ATTN_BACKEND=torch  pip install -e . --no-build-isolation

The chosen value is baked into ``flash_mask/_backend.py`` by ``setup.py``.
No environment variable is needed (or checked) at runtime.
"""

import importlib
import numpy as np
import paddle
from .cute.interface import flashmask_attention as _cute_flashmask_attention

__all__ = [
    "flash_attn_func",
    "flash_attn_varlen_func",
    "flash_attn_combine",
    "flash_attention",
    "flashmask_attention",
]

_BACKENDS = {
    "paddle": "flash_mask.flash_attn_v4.paddle.interface",
    "torch":  "flash_mask.flash_attn_v4.torch.interface",
}

# ---------------------------------------------------------------------------
# Resolve backend name from compile-time _backend.py (generated by setup.py).
# Falls back to 'paddle' (matching setup.py default) if _backend.py is absent
# (e.g. running directly from a source checkout without pip install).
# ---------------------------------------------------------------------------
try:
    from flash_mask._backend import BACKEND as _backend_name
except ImportError:
    _backend_name = 'paddle'

if _backend_name not in _BACKENDS:
    raise ValueError(
        f"Unknown backend {_backend_name!r}, "
        f"expected one of {sorted(_BACKENDS)}"
    )

try:
    _mod = importlib.import_module(_BACKENDS[_backend_name])
except ImportError as e:
    raise ImportError(
        f"Backend {_backend_name!r} is not available. "
        f"Re-install with FLASH_ATTN_BACKEND={_backend_name} to confirm, "
        f"or switch backend via FLASH_ATTN_BACKEND at install time."
    ) from e

flash_attn_func        = _mod.flash_attn_func
flash_attn_varlen_func = _mod.flash_attn_varlen_func
flash_attn_combine     = _mod.flash_attn_combine

def _convert_to_varlen_bound2(
    query: paddle.Tensor,
    key: paddle.Tensor,
    value: paddle.Tensor,
    startend_row_indices: paddle.Tensor,
    causal: bool,
):
    """Convert padded tensors to varlen format using lts+ute boundary detection.

    Supports asymmetric seqlen_q != seqlen_k and zero-length documents.
    Requires bound_num == 2 (both lts and ute available).

    Handles Q padding: when last doc's lts < seqlen_q, adds a trailing doc with sk=0
    and zeros out the padding Q positions via output_to_padded.
    """
    b, sq, hq, d = query.shape
    _, sk, hkv, dv = value.shape

    sri_np = startend_row_indices.numpy()  # (batch, 1, sk, 2)
    lts_np = sri_np[:, 0, :, 0]  # (batch, sk)
    ute_np = sri_np[:, 0, :, 1]  # (batch, sk)

    cu_seqlens_q_list = []
    cu_seqlens_k_list = []
    max_doc_sq = 0
    max_doc_sk = 0
    needs_q_padding = False
    q_padding_starts = []

    for bi in range(b):
        lts = lts_np[bi]  # (sk,)
        ute = ute_np[bi]  # (sk,)

        # Detect K-side document boundaries
        # Boundary at col j > 0 if:
        #   1. lts[j] != lts[j-1]  (Q endpoint changed)
        #   2. ute[j] == lts[j] AND ute[j-1] < lts[j-1]  (transition to zero-Q doc)
        k_starts = [0]
        for j in range(1, sk):
            if lts[j] != lts[j - 1]:
                k_starts.append(j)
            elif ute[j] == lts[j] and ute[j - 1] < lts[j - 1]:
                k_starts.append(j)

        # Build q_bounds and k_bounds
        q_bounds = [np.int32(0)]
        k_bounds = [np.int32(k) for k in k_starts] + [np.int32(sk)]

        for doc_idx in range(len(k_starts)):
            doc_lts = np.int32(lts[k_starts[doc_idx]])
            q_bounds.append(doc_lts)

        # Handle Q padding: if last doc doesn't cover all Q positions
        q_pad_start = int(q_bounds[-1])
        q_padding_starts.append(q_pad_start)
        if q_pad_start < sq:
            needs_q_padding = True
            q_bounds.append(np.int32(sq))
            k_bounds.append(np.int32(sk))  # padding doc has sk=0 (sk - sk = 0)

        # Compute per-doc max lengths
        for i in range(len(q_bounds) - 1):
            doc_sq = int(q_bounds[i + 1]) - int(q_bounds[i])
            doc_sk = int(k_bounds[i + 1]) - int(k_bounds[i])
            max_doc_sq = max(max_doc_sq, doc_sq)
            max_doc_sk = max(max_doc_sk, doc_sk)

        # Add batch offsets
        cu_seqlens_q_list.append(
            np.array(q_bounds[:-1], dtype=np.int32) + np.int32(bi * sq)
        )
        cu_seqlens_k_list.append(
            np.array(k_bounds[:-1], dtype=np.int32) + np.int32(bi * sk)
        )

    # Concatenate with final sentinel
    cu_seqlens_q_np = np.concatenate(
        cu_seqlens_q_list + [np.array([b * sq], dtype=np.int32)]
    )
    cu_seqlens_k_np = np.concatenate(
        cu_seqlens_k_list + [np.array([b * sk], dtype=np.int32)]
    )
    cu_seqlens_q = paddle.to_tensor(cu_seqlens_q_np)
    cu_seqlens_k = paddle.to_tensor(cu_seqlens_k_np)

    # Flatten tensors
    q_varlen = query.reshape([b * sq, hq, d])
    k_varlen = key.reshape([b * sk, hkv, d])
    v_varlen = value.reshape([b * sk, hkv, dv])

    # Causal detection: for causal=False, check if ute matches causal pattern
    varlen_causal = causal
    if not causal:
        is_causal = True
        for bi in range(b):
            lts = lts_np[bi]
            ute = ute_np[bi]
            # Re-detect boundaries for verification
            k_starts_bi = [0]
            for j in range(1, sk):
                if lts[j] != lts[j - 1]:
                    k_starts_bi.append(j)
                elif ute[j] == lts[j] and ute[j - 1] < lts[j - 1]:
                    k_starts_bi.append(j)
            k_starts_bi.append(sk)

            prev_q_end = 0
            for doc_idx in range(len(k_starts_bi) - 1):
                k_start = k_starts_bi[doc_idx]
                k_end = k_starts_bi[doc_idx + 1]
                doc_sk = k_end - k_start
                q_offset = prev_q_end
                doc_lts = int(lts[k_start])
                doc_sq = doc_lts - q_offset
                prev_q_end = doc_lts

                if doc_sq == 0:
                    for j in range(k_start, k_end):
                        if ute[j] != lts[j]:
                            is_causal = False
                            break
                else:
                    for j_local in range(doc_sk):
                        expected = q_offset + max(0, j_local - (doc_sk - doc_sq))
                        if int(ute[k_start + j_local]) != expected:
                            is_causal = False
                            break
                if not is_causal:
                    break
            if not is_causal:
                break
        if is_causal:
            varlen_causal = True

    result = {
        "q": q_varlen,
        "k": k_varlen,
        "v": v_varlen,
        "cu_seqlens_q": cu_seqlens_q,
        "cu_seqlens_k": cu_seqlens_k,
        "max_seqlen_q": max_doc_sq,
        "max_seqlen_k": max_doc_sk,
        "causal": varlen_causal,
    }

    # # Add output_to_padded if Q padding exists
    # if needs_q_padding:
    #     _b, _sq = b, sq
    #     _q_padding_starts = q_padding_starts

    #     def output_to_padded(out_varlen_pt):
    #         nh = out_varlen_pt.shape[1]
    #         dv_out = out_varlen_pt.shape[2]
    #         out_padded = out_varlen_pt.reshape([_b, _sq, nh, dv_out])
    #         for bi_inner in range(_b):
    #             q_end = _q_padding_starts[bi_inner]
    #             if q_end < _sq:
    #                 out_padded[bi_inner, q_end:, :, :] = 0
    #         return out_padded

    #     result["output_to_padded"] = output_to_padded

    return result


def _convert_to_varlen_bound1(
    query: paddle.Tensor,
    key: paddle.Tensor,
    value: paddle.Tensor,
    startend_row_indices: paddle.Tensor,
    causal: bool,
):
    """Convert padded tensors to varlen format using lts-only boundary detection.

    Only supports symmetric seqlen_q == seqlen_k. Kept for backward compatibility
    with bound_num == 1 masks.
    """
    b, sq, hq, d = query.shape
    _, skv, hkv, dv = value.shape
    assert sq == skv, (
        f"bound_num==1 requires seqlen_q == seqlen_k, "
        f"got seqlen_q={sq}, seqlen_k={skv}"
    )

    sri_np = startend_row_indices.numpy()
    s_np = sri_np[:, 0, :, 0]  # (batch, seqlen_k)

    # Boundary detection from lts changes
    diffs = s_np[:, 1:] != s_np[:, :-1]

    real_ends_np = s_np.max(axis=1)
    real_ends = real_ends_np.tolist()
    needs_padding_fixup = bool(np.any(real_ends_np < skv))

    cu_seqlens_list = []
    max_doc_len = 0
    for bi in range(b):
        change_idx = np.nonzero(diffs[bi])[0].astype(np.int32) + 1
        boundaries = np.concatenate([
            np.zeros(1, dtype=np.int32),
            change_idx,
            np.array([skv], dtype=np.int32),
        ])
        doc_lens = boundaries[1:] - boundaries[:-1]
        max_doc_len = max(max_doc_len, int(doc_lens.max()))
        cu_seqlens_list.append(boundaries[:-1] + np.int32(bi * skv))

    cu_seqlens_np = np.concatenate(
        cu_seqlens_list + [np.array([b * skv], dtype=np.int32)]
    )
    cu_seqlens = paddle.to_tensor(cu_seqlens_np)

    q_varlen = query.reshape([b * sq, hq, d])
    k_varlen = key.reshape([b * skv, hkv, d])
    v_varlen = value.reshape([b * skv, hkv, dv])

    varlen_causal = causal

    result = {
        "q": q_varlen,
        "k": k_varlen,
        "v": v_varlen,
        "cu_seqlens_q": cu_seqlens,
        "cu_seqlens_k": cu_seqlens,
        "max_seqlen_q": max_doc_len,
        "max_seqlen_k": max_doc_len,
        "causal": varlen_causal,
    }

    if needs_padding_fixup:
        _b, _sq = b, sq
        _real_ends = real_ends

        def output_to_padded(out_varlen_pt):
            nh = out_varlen_pt.shape[1]
            dv_out = out_varlen_pt.shape[2]
            out_padded = out_varlen_pt.reshape(_b, _sq, nh, dv_out)
            row_idx = paddle.arange(_sq)
            real_end_t = paddle.to_tensor(
                _real_ends, dtype=paddle.int64,
            ).unsqueeze(1)
            padding_mask = row_idx.unsqueeze(0) >= real_end_t
            out_padded[padding_mask] = 0
            return out_padded

        result["output_to_padded"] = output_to_padded

    return result


def convert_to_varlen(
    query: paddle.Tensor,
    key: paddle.Tensor,
    value: paddle.Tensor,
    startend_row_indices: paddle.Tensor,
    causal: bool,
):
    _, hfm, _, bound_num = startend_row_indices.shape
    b, sq, hq, d = query.shape
    sk = value.shape[1]

    assert hfm == 1
    assert bound_num == 1 or bound_num == 2

    if bound_num == 2:
        assert not causal, (
            # TODO
        )
        return _convert_to_varlen_bound2(
            query, key, value, startend_row_indices, causal
        )
    else:
        assert sq == sk, (
            f"Asymmetric seqlen_q != seqlen_k requires bound_num == 2, "
            f"got bound_num=1 with seqlen_q={sq}, seqlen_k={sk}"
        )
        return _convert_to_varlen_bound1(
            query, key, value, startend_row_indices, causal
        )

def flashmask_attention(
    query: paddle.Tensor,
    key: paddle.Tensor,
    value: paddle.Tensor,
    startend_row_indices: paddle.Tensor | None = None,
    *,
    dropout: float = 0.0,
    causal: bool = False,
    window_size: int | tuple | None = None,
    return_softmax_lse: bool = False,
    return_seed_offset: bool = False,
    fixed_seed_offset: paddle.Tensor | None = None,
    rng_name: str = "",
    training: bool = True,
    name: str | None = None,
    softmax_scale: float | None = None,
    block_mask: paddle.Tensor | None = None,
    use_varlen: bool = False,
):
    if use_varlen:
        assert (
            paddle.base.framework.get_flags(["FLAGS_flash_attn_version"])["FLAGS_flash_attn_version"] == 4
        ), (
            "use_varlen only support fa4"
        )
        assert (
            not paddle.get_flags(["FLAGS_cudnn_deterministic"])["FLAGS_cudnn_deterministic"]
        ), (
            "use_varlen does not support deterministic"
        )
        assert dropout == 0, (
            "use_varlen does not support dropout"
        )
        assert window_size is None, (
            "use_varlen does not support setting window_size"
        )
        assert block_mask is None, (
            "use_varlen does not support block_mask"
        )

        batch_size, seqlen_q, nheads, d = query.shape
        seqlen_k = key.shape[1]

        dv = value.shape[-1]

        if (d == 256 or dv == 256):
            assert not return_softmax_lse, (
                "SM100 backward with head_dim=256 does not support dlse, ",
                "please set return_softmax_lse to False"
            )

        varlen_args = convert_to_varlen(
            query=query,
            key=key,
            value=value,
            startend_row_indices=startend_row_indices,
            causal=causal)

        print(f"wsm debug cu_seqlens_q: {varlen_args['cu_seqlens_q']}")
        print(f"wsm debug cu_seqlens_k: {varlen_args['cu_seqlens_k']}")

        out, lse = flash_attn_varlen_func(
            q=varlen_args["q"],
            k=varlen_args["k"],
            v=varlen_args["v"],
            cu_seqlens_q=varlen_args["cu_seqlens_q"],
            cu_seqlens_k=varlen_args["cu_seqlens_k"],
            max_seqlen_q=varlen_args["max_seqlen_q"],
            max_seqlen_k=varlen_args["max_seqlen_k"],
            softmax_scale=softmax_scale,
            causal=varlen_args["causal"],
            return_lse=return_softmax_lse,
        )

        if "output_to_padded" in varlen_args:
            out = varlen_args["output_to_padded"](out)
        else:
            out = out.reshape([batch_size, seqlen_q, nheads, dv])

        if return_softmax_lse:
            return [out, lse]
        else:
            return out
    else:
        return _cute_flashmask_attention(
            query=query,
            key=key,
            value=value,
            startend_row_indices=startend_row_indices,
            dropout=dropout,
            causal=causal,
            window_size=window_size,
            return_softmax_lse=return_softmax_lse,
            return_seed_offset=return_seed_offset,
            fixed_seed_offset=fixed_seed_offset,
            rng_name=rng_name,
            training=training,
            name=name,
            softmax_scale=softmax_scale,
            block_mask=block_mask,
        )
